sudo: false
language: python
python:
  - "2.7"
  - "3.6"

cache: pip

before_install:
- pip install --upgrade pip setuptools wheel

install:
- pip install -r ./requirements.txt
- pip install -r ./requirements/test.txt

script: py.test ./src --cov=./src

